# ~/.config/starship.toml

[battery]
full_symbol = "🔋"
charging_symbol = "🔌"
discharging_symbol = "💀"

[[battery.display]]
threshold = 30
style = "bold red"

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[cmd_duration]
min_time = 10_000
format = " took [$duration]($style)"

[julia]
format = "[$symbol$version]($style) "
symbol = "ஃ "
style = "bold green"

[package]
disabled = true

[python]
format = "[$symbol$version]($style) "
style = "bold green"

[rust]
format = "[$symbol$version]($style) "
style = "bold green"

[time]
time_format = "%T"
format = "$time($style) "
style = "bright-white"
disabled = false

[username]
style_user = "bold dimmed blue"
show_always = false

[nodejs]
disabled = true
